Problem statement
- understand student's performance is affected by other variables such as gender, ethnicity etc.

In [8]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')

In [9]:
df = pd.read_csv('./data/stud.csv')

In [10]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [12]:
df.shape

(1000, 8)

In [13]:
df.isna().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [14]:
# check for duplicates
df.duplicated().sum()

np.int64(0)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [16]:
df.nunique()

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     81
reading_score                  72
writing_score                  77
dtype: int64

In [17]:
df.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [18]:
df['math_score'].dtype

dtype('int64')

In [21]:
# identify numerical and categorical columns
numeric_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print(numeric_features)
print(len(numeric_features))
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print(cat_features)
print(len(cat_features))

['math_score', 'reading_score', 'writing_score']
3
['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
5

In [ ]:
# adding new columns
df['total_score'] = df['math_score'] + df['writing_score']
df['avg_Score'] = round(df['total_score']/3, 2)
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,avg_Score
0,female,group B,bachelor's degree,standard,none,72,72,74,146,48.67
1,female,group C,some college,standard,completed,69,90,88,157,52.33
2,female,group B,master's degree,standard,none,90,95,93,183,61.00
3,male,group A,associate's degree,free/reduced,none,47,57,44,91,30.33
4,male,group C,some college,standard,none,76,78,75,151,50.33